#!/bin/env python3

"""
pyMooltipass is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

pyMooltipass is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with pyMooltipass.  If not, see <http://www.gnu.org/licenses/>.

This file is part of pyMooltipass
"""

import pyMooltipass as Mltp

with Mltp.Mooltipass() as mltp:
    _layout = mltp.get_keyboard_layout()
    print("Layout {0}".format(_layout))

    #mltp.select_keyboard_layout('FRDE_CH')
    #print("Layout {0}".format(mltp.get_keyboard_layout()))
    #mltp.select_keyboard_layout(_layout)

    print(mltp.get_favorites_list())

